<?php

namespace Wcs\InfoMailBundle\Repository;

/**
 * TypeMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMailRepository extends \Doctrine\ORM\EntityRepository
{
}
