infomail_index:
    path:     /
    defaults: { _controller: "WcsInfoMailBundle:InfoMail:index" }
    methods:  GET

infomail_show:
    path:     /{id}/show
    defaults: { _controller: "WcsInfoMailBundle:InfoMail:show" }
    methods:  GET

infomail_new:
    path:     /new
    defaults: { _controller: "WcsInfoMailBundle:InfoMail:new" }
    methods:  [GET, POST]

infomail_edit:
    path: /{id}/edit
    defaults: { _controller: "WcsInfoMailBundle:InfoMail:edit" }
    methods:  [GET, POST]

infomail_update:
    path: /{id}/update
    defaults: { _controller: "WcsInfoMailBundle:InfoMail:update" }
    methods:  PUT

infomail_delete:
    path:     /{id}/delete
    defaults: { _controller: "WcsInfoMailBundle:InfoMail:delete" }
    methods:  [GET, DELETE]

infomail_send:
    path:     /{id}/send
    defaults: { _controller: "WcsInfoMailBundle:InfoMail:send" }
    methods:  GET
