wcs_info_mail_infomail:
    resource: "@WcsInfoMailBundle/Resources/config/routing/infomail.yml"
    prefix:   /infomail

wcs_info_mail_homepage:
    path:     /
    defaults: { _controller: WcsInfoMailBundle:Mail:index }
