Wcs\InfoMailBundle\Entity\InfoMail:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        subject:
            type: string
            length: 255
        body:
            type: text

    oneToMany:
        files:
            targetEntity: Wcs\InfoMailBundle\Entity\File
            mappedBy: infoMail
            cascade: [ persist, remove ]
    manyToOne:
        typeMail:
            targetEntity: Wcs\InfoMailBundle\Entity\TypeMail
            joinColumn:
                name: typeMail_id
                referencedColumnName: id

    lifecycleCallbacks:
        preFlush: [ upload ]
