Wcs\InfoMailBundle\Entity\InfoMail:
    type: entity
    repository_class: Wcs\InfoMailBundle\Repository\InfoMailRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        subject:
            type: string
            length: 255
        body:
            type: text
        documentsNames:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
